package ua.epam.training.kukuruza.model.dao.daoMySql;

import ua.epam.training.kukuruza.model.connection.IConnectionFactory;
import ua.epam.training.kukuruza.model.dao.IDaoSubject;
import ua.epam.training.kukuruza.model.dao.mapper.SubjectMapper;
import ua.epam.training.kukuruza.model.entity.Subject;

import java.util.List;
import java.util.Optional;

public class MySqlDaoSubject implements IDaoSubject {
    private static final String GET_SUBJECT_BY_ID_SQL = "SELECT * FROM subject WHERE id = ?";
    private static final String GET_ALL_SUBJECTS_SQL = "SELECT * FROM subject";
    private static final String INSERT_SUBJECT_SQL = "INSERT INTO subject VALUES (NULL, ?)";
    private static final String UPDATE_SUBJECT_SQL = "UPDATE subject SET name = ? WHERE id = ?";
    private static final String DELETE_SUBJECT_SQL = "DELETE FROM subject WHERE id = ?";
    private MySqlDaoHelper helper = MySqlDaoHelper.getInstance();
    private IConnectionFactory factory;

    public MySqlDaoSubject(IConnectionFactory factory) {
        this.factory = factory;
    }

    @Override
    public Optional<Subject> get(Integer id) {
        return helper.get(GET_SUBJECT_BY_ID_SQL, SubjectMapper::map, id);
    }

    @Override
    public List<Subject> getAll() {
        return helper.getAll(GET_ALL_SUBJECTS_SQL, SubjectMapper::map);
    }

    @Override
    public Integer save(Subject entity) {
        Integer autoGeneratedId = helper.save(INSERT_SUBJECT_SQL, entity.getName());
        entity.setId(autoGeneratedId);
        return autoGeneratedId;
    }

    @Override
    public void update(Subject entity) {
        helper.update(UPDATE_SUBJECT_SQL, entity.getName(), entity.getId());
    }

    @Override
    public boolean delete(Integer id) {
        return helper.delete(DELETE_SUBJECT_SQL, id);
    }
}
